name: MySQL Integration Test

on:
  pull_request:
    branches: [main]

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: create and configure
        run: |
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOST }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo password=${{ secrets.PASSWORD }}>> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
          packer version
      
      - name: Run Packer pulgin installation
        run: packer init .

      - name: Run Packer validate
        run: packer validate -var "PASSWORD=${{ secrets.PASSWORD }}" -var "DATABASE=${{ secrets.DATABASE }}" -var "USER=${{ secrets.USER }}" -var-file="variables.pkrvars.hcl" aws-debian.pkr.hcl